[profile.default]
src = "src"
out = "out"
libs = ["@uniswap/v4-core/src=lib/v4-periphery/lib/v4-core/src"]

evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
